name: Maven Build and Pack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Compiliamo usando Maven, leggendo il maven-settings.xml originale e forzando il fix per Lombok
    - name: Build with Maven
      run: mvn -B package --file pom.xml --settings $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -DskipTests -Dmaven.compiler.annotationProcessorPaths=org.projectlombok:lombok:1.18.30
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Salva il file .jar finale e lo rende scaricabile direttamente su GitHub Actions
    - name: Upload Artifact (Scarica il tuo JAR qui)
      uses: actions/upload-artifact@v4
      with:
        name: Cannons-Revamped-Jar
        path: cannons-bukkit/target/*.jar

